[package]
name = "couchbase-shell"
version = "0.0.2"
authors = ["Michael Nitschinger <michael@nitschinger.at>"]
edition = "2018"

[dependencies]
log = "0.4"
pretty_env_logger = "0.3"
structopt = "0.3"
futures = "0.3"
http = "0.2"
warp = "0.2"
tokio = { version = "0.2", features = ["full"] }
reqwest = { version = "0.10", features = ["json"] }
toml = "0.5"
dirs = "2.0"
rust-embed = "5.5"
mime_guess = "2.0"

nu = { git = "https://github.com/daschl/nushell.git", branch = "custom", features = ["default", "stable"] }
nu-protocol = { git = "https://github.com/daschl/nushell.git", branch = "custom" }
nu-errors = { git = "https://github.com/daschl/nushell.git", branch = "custom" }
nu-source = { git = "https://github.com/daschl/nushell.git", branch = "custom"}
nu-cli = { git = "https://github.com/daschl/nushell.git", branch = "custom"}

serde = "1.0"
serde_json = "1.0"

tera = "1.1"
fake = { version = "2.2", features = ["chrono"] }
uuid = { version = "0.8", features = ["v4"] }
chrono = { version = "0.4.11", features = ["serde"] }

couchbase = { git = "https://github.com/couchbaselabs/couchbase-rs", features = ["libcouchbase-static"] }

[[bin]]
name = "cbsh"
path = "src/main.rs"