[package]
name = "couchbase-shell"
version = "1.0.0-beta.4-dev"
authors = ["Michael Nitschinger <michael@nitschinger.at>"]
edition = "2018"
default-run = "cbsh"

[dependencies]
ansi_term = "0.12"
async-stream = "0.2"
async-trait = "0.1.31"
base64 = "0.13.0"
bytes = "1.0"
chrono = { version = "0.4.11", features = ["serde"] }
crc = "1.8.1"
ctrlc = "3.2.1"
dirs = "2.0"
env_logger = "0.8"
fake = { version = "2.4", features = ["chrono"] }
futures = "0.3"
hmac = "0.11.0"
http = "0.2"
http-types = "2.5"
humantime-serde = "1.0"
isahc = "1.6"
lazy_static = "1.4.0"
log = "0.4"
mime_guess = "2.0"
nu = { git = "https://github.com/nushell/nushell", rev="1a16b9a2c4d3cb263fa5f0a11a4d41210f2cd300", features = ["extra"] }
nu-protocol = { git = "https://github.com/nushell/nushell", rev="1a16b9a2c4d3cb263fa5f0a11a4d41210f2cd300"  }
nu-command = { git = "https://github.com/nushell/nushell", rev="1a16b9a2c4d3cb263fa5f0a11a4d41210f2cd300"  }
nu-parser = { git = "https://github.com/nushell/nushell", rev="1a16b9a2c4d3cb263fa5f0a11a4d41210f2cd300"  }
nu-path = { git = "https://github.com/nushell/nushell", rev="1a16b9a2c4d3cb263fa5f0a11a4d41210f2cd300"  }
nu-cli = { git = "https://github.com/nushell/nushell", rev="1a16b9a2c4d3cb263fa5f0a11a4d41210f2cd300"  }
nu-engine = { git = "https://github.com/nushell/nushell", rev="1a16b9a2c4d3cb263fa5f0a11a4d41210f2cd300"  }
nu-plugin = { git = "https://github.com/nushell/nushell", rev="1a16b9a2c4d3cb263fa5f0a11a4d41210f2cd300" }
num-bigint = "0.4"
num-traits = "0.2.14"
pretty_env_logger = "0.3"
rand = "0.8.3"
regex = "1.3.7"
reqwest = { version = "0.11", features = ["json"] }
rpassword = "4.0"
rust-embed = "5.5"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
serde_urlencoded = "0.6"
sha2 = "0.9.5"
structopt = "0.3"
tera = "1.1"
temp-dir = "0.1"
tokio = { version = "1", features = ["full"] }
tokio-util = { version = "0.6.6", features = ["codec"] }
tokio-native-tls = "0.3.0"
toml = "0.5"
trust-dns-resolver = { version = "0.20.3", features = ["dns-over-rustls"] }
url = "2.1"
uuid = { version = "0.8", features = ["v4"] }

[dev-dependencies]
nu-test-support = { git = "https://github.com/nushell/nushell", rev="1a16b9a2c4d3cb263fa5f0a11a4d41210f2cd300" }
dunce = "1.0.1"
itertools = "0.10.3"
lazy_static = "1.4.0"
strum = "0.22.0"
strum_macros = "0.22"

[[bin]]
name = "cbsh"
path = "src/main.rs"

[profile.release]
lto = true
codegen-units = 1

[[test]]
name = "test"
path = "tests/integration/main.rs"
harness = false
