[package]
name = "couchbase-shell"
version = "1.0.0-beta.3"
authors = ["Michael Nitschinger <michael@nitschinger.at>"]
edition = "2018"
default-run = "cbsh"

[dependencies]
ansi_term = "0.12"
async-stream = "0.2"
async-trait = "0.1.31"
base64 = "0.13.0"
bytes = "1.0"
chrono = { version = "0.4.11", features = ["serde"] }
crc = "1.8.1"
dirs = "2.0"
env_logger = "0.8"
fake = { version = "2.4", features = ["chrono"] }
futures = "0.3"
hmac = "0.11.0"
http = "0.2"
http-types = "2.5"
humantime-serde = "1.0"
isahc = "1.3"
lazy_static = "1.4.0"
log = "0.4"
mime_guess = "2.0"
nu = { version = "0.40.0", features = ["extra"] }
nu-protocol = { version = "0.40.0" }
nu-data = { version = "0.40.0" }
nu-errors = { version = "0.40.0" }
nu-stream = { version = "0.40.0" }
nu-source = { version = "0.40.0" }
nu-cli = { version = "0.40.0" }
nu-engine = { version = "0.40.0" }
nu-plugin = { version = "0.40.0" }
nu_plugin_from_bson = { version = "0.40.0" }
nu-value-ext = { version = "0.40.0" }
num-bigint = "0.4"
num-traits = "0.2.14"
pretty_env_logger = "0.3"
rand = "0.8.3"
regex = "1.3.7"
reqwest = { version = "0.11", features = ["json"] }
rpassword = "4.0"
rust-embed = "5.5"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
serde_urlencoded = "0.6"
sha2 = "0.9.5"
structopt = "0.3"
tera = "1.1"
temp-dir = "0.1"
tokio = { version = "1", features = ["full"] }
tokio-util = { version = "0.6.6", features = ["codec"] }
tokio-native-tls = "0.3.0"
toml = "0.5"
trust-dns-resolver = { version = "0.20.3", features = ["dns-over-rustls"] }
url = "2.1"
uuid = { version = "0.8", features = ["v4"] }

[dev-dependencies]
nu-test-support = "0.29.0"
dunce = "1.0.1"
lazy_static = "1.4.0"

[[bin]]
name = "cbsh"
path = "src/main.rs"

[profile.release]
lto = true
codegen-units = 1

[[bin]]
doc=false
name="runtests"
path="tests/bin/mod.rs"
